#### zeros() : 괄호 안에 입력된 숫자만큼의 원소를 생성하고 0으로 초기화

In [6]:
import numpy as np

# y = np.zeros(shape=(10,), dtype=np.int8)
#                     shape => 배열의 수 / n차열 배열을 지정할 수있다.
#                     Dtype => 데이터타입을 정해줄 수있음

y = np.zeros(10)
y

# x = np.array([1,2,3])
# type(x)
# x.shape


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##### 혹시라도 오류가 생기면 !pip install numpy  로 numpy를 설치해야한다.

#### mean() : 배열에 저장된 원소들의 평균값을 계산

In [12]:
import numpy as np

list_1 = [1,2,3]
x = np.array(list_1)      #Array => 배열을 만들어준다

x.mean()                  #배열의 평균값 
np.mean(x)
x.shape

(3,)

#### array() : 배열의 원소를 입력할 때는 반드시.. 리스트 형식으로 입력?

In [16]:
x = np.array([1,2,3])
y = np.array((1,2,3))
z = np.array({1,2,3})
a = np.array({'a':'b','c':'d','c':'a'}) #같은 키값이 있으면 1개의 값만 출력된다.

print(x,y,z,a)

#리스트와 튜플형태만 배열로 출력된다.

[1 2 3] [1 2 3] {1, 2, 3} {'a': 'b', 'c': 'a'}


#### reshape():  배열을 원하는 모양으로 생성

In [30]:
import numpy as np

a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4))
# a리스트를 2행 4열로 재배열한다.

               
print(b, b.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)


#### reshape() : 3차원 변환

In [32]:
a = np.arange(1,9)       #1부터 9-1까지 출력된다.
print(a)
b = a.reshape(2,2,2)
print(b)

#reshape를 활용하는 경우를 보다 보면 입력인수로 -1이 들어간 경우가 종종 있다.
# reshape()의 ‘-1’이 의미하는 바는,
# 변경된 배열의 ‘-1’ 위치의 차원은 “원래 배열의 길이와 남은 차원으로 부터 추정”이 된다는 뜻이다.

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
# a = np.arange(1,9)       #1부터 9-1까지 출력된다.
# print(a)
# b = a.reshape(4,2,2)
# print(b)

[1 2 3 4 5 6 7 8]


ValueError: cannot reshape array of size 8 into shape (4,2,2)

In [35]:
x = np.arange(12)
x = x.reshape(3,4)

print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
x.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [37]:
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [38]:
x.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

##### 행(row)의 위치에 -1을 넣고 열의 값을 지정해주면 변환될 배열의 행의 수는 알아서 지정이 된다는 소리이다.

#### ones(): 배열의 1의 값들로 채움

In [41]:
y = np.ones([3,4])
print(y)           #3행4열의 배열을 1로 채워서 만듦

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
# 응용 : 다른 값으로 충분히 응용이 가능하다.

y = np.ones([3,4])
z = y * 2
print(z)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


#### Numpy의 슬라이싱

In [44]:
list1 = [[1,11],[2,12],[3,13],[4,14]]
print(list1[:][1])
print(list1[:, 1])   # list일뿐 아직 배열은 아니라 오류 발생한다.

[2, 12]


TypeError: list indices must be integers or slices, not tuple

In [54]:
list1 = [[1,11],[2,12],[3,13],[4,14]]
arr = np.array(list1)
print(arr)         #4행2열

print(arr [:],[1])
print(arr[:, 1])      #   
print(arr[1, 1])      #2행의 2열 출력
print(arr[0, 0])      #1행의 1열 출력
print(arr[:2, :2])    #2행 2열까지 출력

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]]
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]] [1]
[11 12 13 14]
12
1
[[ 1 11]
 [ 2 12]]


#### math모듈의 sqrt()와 Numpy모듈의 sqrt()비교 // sqrt = 루트....

In [58]:
import math
math.sqrt(2)
math.sqrt([2,3,4])    #리스트 각각의 루트값 출력이 불가능하다. = 오류값 출력오류값 출력

TypeError: must be real number, not list

In [60]:
import numpy
print(numpy.sqrt(2))      #훨씬 더 많은 기능이 있다.
print(numpy.sqrt([2,3,4]))   #각각의 배열의 루트값 출력이 가능하다.

1.4142135623730951
[1.41421356 1.73205081 2.        ]


#### 배열 행,열을 변경하기 // 응용편

In [62]:
import numpy as np

x = np.zeros(15)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [66]:
import numpy as np

y = np.zeros([5,3])
print(y)           

#배열 지정

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [67]:
x = np.zeros(15)
y = np.zeros([5,3])

z = y.reshape([3,5])

print(z)

#배열 변경

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [68]:
y = np.zeros([5,3])
z = y + 4
print(z)

#초기값 변경

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


### 전치행렬
#### transpose()

In [71]:
import numpy as np

ary = np.array([[1,2],[3,4]])   # ([[],[]]) 형식
print(ary)

print('\n\n\n')

trans_ary = ary.transpose()
print(trans_ary)                #행과열의 변경한다.행->열 , 열->행

[[1 2]
 [3 4]]




[[1 3]
 [2 4]]


In [72]:
ary = np.array([[1,2,5],[3,4,6]])
print(ary)

print('\n\n\n')

trans_ary = ary.transpose()
print(trans_ary)                #행과열의 변경한다 // 열->행, 행->열 

[[1 2 5]
 [3 4 6]]




[[1 3]
 [2 4]
 [5 6]]


##### 2개 배열에 대한 연산
##### 2개 배열에 저장된 내용을 인덱스별로 계산
##### 선형대수학의 사칙연산과 동일하게 작동 / 곱셈도 같은 원리로 작동

In [78]:
import numpy as np

x = np.array((3,4,5))
y = np.array((1,2,3))

print(x+y)                #행과열이 같아야만 사칙연산이 가능하다.
                          # 각각의 원소끼리 대응한다.
print('\n')    
print(x*y) # 곱하기

print('\n')  
print(x/y) # 나누기

print('\n')  
print(x%y) # 나머지

print('\n')  
print(x**y) # x의 값을 y의 수만큼 제곱해라

[4 6 8]


[ 3  8 15]


[3.         2.         1.66666667]


[0 0 2]
[  3  16 125]


In [79]:
x = np.array((3,4,5))
x **= 5

print(x)

[ 243 1024 3125]


In [80]:
x = np.array((3,4,5))
x += 5

print(x)

[ 8  9 10]


#### 인덱싱

In [81]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(x[1])                   # [4,5,6] -> x배열의 인덱스 1번 내용을 출력 = 2행 출력
print(x[:, 1])                # [2,5,8] -> 각 1차원 배열의 1번 내용을 출력 = 2열 출력

[4 5 6]
[2 5 8]


#### 2개의 Numpy배열 간의 계산

In [85]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])

print(x[0] + y[2])

[ 9 11 13]


In [88]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])

print(x[:,1]*y[2])        # x배열의 2번째 열들을 y행의 3번째 열과 매칭하여 곱하기

[16 45 80]


#### 불린 검사

In [2]:
import numpy as np
a = np.array([10, 20, 30, 40, 60])
b = a > 30

print(b)

[False False False  True  True]


#### numpy random

In [7]:
import numpy as np

ary = np.random.random(5)
print(ary)

# 실행시 매번 다른 값을 출력한다.

[0.40257072 0.83586478 0.55439181 0.92638751 0.86605235]


In [11]:
import numpy as np

b = np.random.rand(2, 3)
print(b, b.shape, '\n')

# rand -> 지정한 배열의 랜덤한 값을 출력한다.

b = np.random.rand(2, 2, 3)
print(b, b.shape, '\n')

# (출력할 수 , 행, 열)

# 만들어진 난수 어레이는 주어진 값에 의해 결정되며
# (0, 1) 범위에서 균일한 분포를 갖습니다.

[[0.87593333 0.4450384  0.83922733]
 [0.77340118 0.89295173 0.61958708]] (2, 3) 

[[[0.38637848 0.59380519 0.90871378]
  [0.86242716 0.98792188 0.01272954]]

 [[0.80046923 0.64936623 0.10119131]
  [0.67423342 0.45987762 0.29061776]]] (2, 2, 3) 



In [12]:
import numpy as np

a = np.random.randint(2, size=5)
print(a)
#( 0 ~ X 숫자 사이의 수, 몇 개 출력해라)

b = np.random.randint(2, 4, size=5)
print(b)
# (2~4 범위에서 5개의 정수를 출력해라)

c = np.random.randint(1, 5, size=(2, 3))
print(c)
# (1, 5 범위에서 (2, 3) 형태의 배열을 생성합니다.

[1 0 0 1 0]
[3 2 3 2 2]
[[1 2 2]
 [1 1 4]]


In [22]:
import numpy as np

np.random.seed(0)

print(np.random.rand(2,3))

# seed => 한 번 출력된 랜덤한 값을 고정시킨다.  (Ctrl + Enter로 확인 가능)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [24]:
import numpy as np

np.random.seed(0)
a = np.random.rand(2,3)


print(a>0.12)

#Ctrl + Enter로 확인 가능

[[ True  True  True]
 [ True  True  True]]


#### any()와 all()의 비교

In [31]:
import numpy as np

a = np.random.rand(5)
print(a)
print(a>0.12)
print(np.all(a>0.12))

# 모든 불린값이 True여야지 True

[0.77423369 0.45615033 0.56843395 0.0187898  0.6176355 ]
[ True  True  True False  True]
False


In [30]:
import numpy as np

a = np.random.rand(5)
print(a)
print(a>0.9)
print(np.any(a>0.9))

# 하나의 불린값만 True여도 True

[0.14335329 0.94466892 0.52184832 0.41466194 0.26455561]
[False  True False False False]
True


#### linspace

In [36]:
import numpy as np

a = np.linspace(0, 12, 4)
b = np.linspace(1, 13, 5)
c = np.linspace(2, 12, 5)

print(a)
print(b)
print(c)

# 시작과 끝의 값을 지정하고 그 사이의 값을 균등하게 배분한다. -> array(배열)로 나옴
# print(a) = 0과 12를 포함한 그 사이의 값들을 선형적으로 분배, 모두 4개의 원소를 갖는 배열

[ 0.  4.  8. 12.]
[ 1.  4.  7. 10. 13.]
[ 2.   4.5  7.   9.5 12. ]


In [37]:
import numpy as np

np.linspace(0, 12, 4, endpoint = False)

# endpoint = False => 마지막 값을 제외하고 샘플값을 출력
# 디폴트 -> True

[0. 3. 6. 9.]


In [39]:
import numpy as np

np.linspace(0, 12, 4, retstep = True)
# 배열 간 간격도 나온다.

(array([ 0.,  4.,  8., 12.]), 4.0)